[tox]
isolated_build = true
envlist =
    py313,cover,docs,docs-linkcheck
requires =
    tox-uv>=1

[testenv:py313]
base_python = python3.13
extras = dev
commands =
    {envpython} -m pytest

[testenv:cover]
base_python = python3.13
extras = dev
commands =
    {envpython} -m pytest --cov=fuxi --cov-report=term-missing --cov-report=html

###########################
# Run docs builder
###########################
[testenv:docs]
base_python = {env:TOX_DOCS_PYTHON:python3.13}
extras = docs
commands =
    sphinx-build -b html -d {envtmpdir}/doctrees docs docs/_build/html


###########################
# Run docs linkcheck
###########################

[testenv:docs-linkcheck]
base_python = {env:TOX_DOCS_PYTHON:python3.13}
extras = docs
commands =
    sphinx-build -b linkcheck -d {envtmpdir}/doctrees docs docs/_build/linkcheck
